/**
 * Static presets
 */
module.exports = {
  default: {},
  standardize: {
    alignObjectProperties: false,
    alignTernaryLines: false,
    arrowParens: 'avoid',
    bracketSpacing: true,
    endOfLine: 'lf',
    generatorStarSpacing: true,
    htmlWhitespaceSensitivity: 'css',
    indentChains: true,
    insertPragma: false,
    jsxBracketSameLine: false,
    jsxSingleQuote: false,
    parenSpacing: false,
    printWidth: 92,
    proseWrap: 'preserve',
    quoteProps: 'consistent',
    requirePragma: false,
    semi: false,
    singleQuote: true,
    spaceBeforeFunctionParen: true,
    tabWidth: 2,
    trailingComma: 'es5',
    useTabs: false,
    yieldStarSpacing: true,
  },
  standardx: {
    alignObjectProperties: false,
    alignTernaryLines: false,
    arrowParens: 'avoid',
    bracketSpacing: true,
    endOfLine: 'lf',
    generatorStarSpacing: true,
    htmlWhitespaceSensitivity: 'css',
    indentChains: true,
    insertPragma: false,
    jsxBracketSameLine: false,
    jsxSingleQuote: true,
    parenSpacing: false,
    printWidth: 80,
    proseWrap: 'preserve',
    quoteProps: 'as-needed',
    requirePragma: false,
    semi: false,
    singleQuote: true,
    spaceBeforeFunctionParen: true,
    tabWidth: 2,
    trailingComma: 'none',
    useTabs: false,
    yieldStarSpacing: true,
  },
}
